name: Railway Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy imagraph to Railway
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm i -g @railway/cli@5

      - name: Deploy
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: railway up --service imagraph --project 359d8d88-d634-421d-902f-2c076d566af8 --environment production --detach --yes
